version: "3.8"

services:
  web:
    build:
      context: .
    image: upload-file:latest
    container_name: upload_file

    # Run unprivileged & hardened
    user: "33:33"
    read_only: true
    cap_drop: ["ALL"]
    security_opt:
      - no-new-privileges:false
      - apparmor=upload-file-profile   # <— this profile is defined in conf/upload-file-profile

    ports:
      - "27465:27465"                  # host:container

    # Binds: code RO; uploads/logs RW; apache conf RO; .htpasswd RO
    volumes:
      - type: bind
        source: ./site
        target: /var/www/html
        read_only: true

      - type: bind
        source: ./site/uploads
        target: /var/www/html/uploads
        read_only: false

      - type: bind
        source: ./conf/ports.conf
        target: /etc/apache2/ports.conf
        read_only: true

      - type: bind
        source: ./conf/000-default.conf
        target: /etc/apache2/sites-available/000-default.conf
        read_only: true

      - type: bind
        source: ./conf/.htpasswd
        target: /etc/apache2/.htpasswd
        read_only: true
      
      - type: bind
        source: /home/user1
        target: /home/user1
        read_only: false      # ← read-only home


    # Writable runtime dirs in memory
    tmpfs:
      - /run/apache2:size=8m,mode=0755,uid=33,gid=33
      - /var/log/apache2:size=16m,mode=0755,uid=33,gid=33
      - /tmp:size=32m,mode=1777,uid=33,gid=33

    working_dir: /var/www/html
    restart: unless-stopped

